In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("spam.csv",encoding='latin-1')

In [3]:
for col in data.columns:
    print(col)

v1
v2
Unnamed: 2
Unnamed: 3
Unnamed: 4


In [4]:
data1 = data[["v1","v2"]]

In [5]:
len(data1)

5572

In [6]:
data1

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...
10     ham  I'm gonna be home soon and i don't want to tal...
11    spam  SIX chances to win CASH! From 100 to 20,000 po...
12    spam  URGENT! You have won a 1 week FREE membership ...
13     ham  I've been searching for the right words to tha...
14     ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15    spam  XXXMobileMovieClub: To use your credit, click ...
16     ham                         Oh k...i'm watching here:)
17     ham  Eh u remember how 2 spell his name... Yes i di...
18     ham  Fine if thatåÕs the way u feel. ThatåÕs the wa...
19    spam  England v Macedonia - dont miss the goals/team...
20     ham          Is that seriously how you spell his name?
21     ham  I‰Û÷m going to try for 2 months ha ha only joking
22     ham  So Ì_ pay first lar... Then when is da stock c...
23     ham  Aft i finish my lunch then i go str down lor. ...
24     ham  Ffffffffff. Alright no way I can meet up with ...
25     ham  Just forced myself to eat a slice. I'm really ...
26     ham                     Lol your always so convincing.
27     ham  Did you catch the bus ? Are you frying an egg ...
28     ham  I'm back &amp; we're packing the car now, I'll...
29     ham  Ahhh. Work. I vaguely remember that! What does...
...    ...                                                ...
5542   ham           Armand says get your ass over to epsilon
5543   ham             U still havent got urself a jacket ah?
5544   ham  I'm taking derek &amp; taylor to walmart, if I...
5545   ham      Hi its in durban are you still on this number
5546   ham         Ic. There are a lotta childporn cars then.
5547  spam  Had your contract mobile 11 Mnths? Latest Moto...
5548   ham                 No, I was trying it all weekend ;V
5549   ham  You know, wot people wear. T shirts, jumpers, ...
5550   ham        Cool, what time you think you can get here?
5551   ham  Wen did you get so spiritual and deep. That's ...
5552   ham  Have a safe trip to Nigeria. Wish you happines...
5553   ham                        Hahaha..use your brain dear
5554   ham  Well keep in mind I've only got enough gas for...
5555   ham  Yeh. Indians was nice. Tho it did kane me off ...
5556   ham  Yes i have. So that's why u texted. Pshew...mi...
5557   ham  No. I meant the calculation is the same. That ...
5558   ham                             Sorry, I'll call later
5559   ham  if you aren't here in the next  &lt;#&gt;  hou...
5560   ham                  Anything lor. Juz both of us lor.
5561   ham  Get me out of this dump heap. My mom decided t...
5562   ham  Ok lor... Sony ericsson salesman... I ask shuh...
5563   ham                                Ard 6 like dat lor.
5564   ham  Why don't you wait 'til at least wednesday to ...
5565   ham                                       Huh y lei...
5566  spam  REMINDER FROM O2: To get 2.50 pounds free call...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
data1.isnull()

v1     v2
0     False  False
1     False  False
2     False  False
3     False  False
4     False  False
5     False  False
6     False  False
7     False  False
8     False  False
9     False  False
10    False  False
11    False  False
12    False  False
13    False  False
14    False  False
15    False  False
16    False  False
17    False  False
18    False  False
19    False  False
20    False  False
21    False  False
22    False  False
23    False  False
24    False  False
25    False  False
26    False  False
27    False  False
28    False  False
29    False  False
...     ...    ...
5542  False  False
5543  False  False
5544  False  False
5545  False  False
5546  False  False
5547  False  False
5548  False  False
5549  False  False
5550  False  False
5551  False  False
5552  False  False
5553  False  False
5554  False  False
5555  False  False
5556  False  False
5557  False  False
5558  False  False
5559  False  False
5560  False  False
5561  False  False
5562  False  False
5563  False  False
5564  False  False
5565  False  False
5566  False  False
5567  False  False
5568  False  False
5569  False  False
5570  False  False
5571  False  False

[5572 rows x 2 columns]

In [8]:
import nltk

In [9]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
import re
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
y = data1["v1"]

In [13]:
y

0        ham
1        ham
2       spam
3        ham
4        ham
5       spam
6        ham
7        ham
8       spam
9       spam
10       ham
11      spam
12      spam
13       ham
14       ham
15      spam
16       ham
17       ham
18       ham
19      spam
20       ham
21       ham
22       ham
23       ham
24       ham
25       ham
26       ham
27       ham
28       ham
29       ham
        ... 
5542     ham
5543     ham
5544     ham
5545     ham
5546     ham
5547    spam
5548     ham
5549     ham
5550     ham
5551     ham
5552     ham
5553     ham
5554     ham
5555     ham
5556     ham
5557     ham
5558     ham
5559     ham
5560     ham
5561     ham
5562     ham
5563     ham
5564     ham
5565     ham
5566    spam
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: v1, Length: 5572, dtype: object

In [15]:
y.value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [16]:
le = LabelEncoder()
y_enc = le.fit_transform(y)

In [17]:
y_enc

array([0, 0, 1, ..., 0, 0, 0])

In [18]:
raw_text = data1["v2"]

In [20]:
stop_words = nltk.corpus.stopwords.words("english")
for i in range(len(raw_text)):
    words = nltk.word_tokenize(raw_text[i])
    words = [w for w in words if w not in stop_words]
    raw_text[i] = " ".join(words)

C:\Users\sruth\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3325: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [21]:
Lemmatizer = nltk.stem.WordNetLemmatizer()
for i in range(len(raw_text)):
    words = nltk.word_tokenize(raw_text[i])
    words = [Lemmatizer.lemmatize(w) for w in words]
    raw_text[i] = " ".join(words)


In [24]:
vectorizer = TfidfVectorizer(ngram_range=(1,2))
X_ngrams = vectorizer.fit_transform(raw_text)

In [25]:
X_ngrams.shape

(5572, 43202)

In [26]:
X_train, X_test,y_train,y_test = train_test_split(X_ngrams,y_enc,test_size=0.2,random_state=42, stratify=y_enc)

In [27]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
metrics.f1_score(y_test,y_pred)

0.7983870967741936

In [29]:
cm = metrics.confusion_matrix(y_test,y_pred)

In [30]:
cm

array([[966,   0],
       [ 50,  99]], dtype=int64)

In [31]:
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier()
classifier2.fit(X_train,y_train)
y_pred2=classifier2.predict(X_test)
metrics.f1_score(y_test,y_pred2)

C:\Users\sruth\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.8188976377952757

In [32]:
cm2 = metrics.confusion_matrix(y_test,y_pred2)

In [33]:
cm2

array([[965,   1],
       [ 45, 104]], dtype=int64)